kind: Secret
ansible_user: ENC[AES256_GCM,data:gi6aNEVlXg==,iv:9RvFFpzFdZGfbALfSnPGAaQcDCiO54PLShtWr74Se8M=,tag:u/lBTBYivSSQB4t2JXkddQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Hf7dxgTSwyhU,iv:ow2+gEPySF5XEOymYeylgt/RigX9k9M9I8tt3R+IlsQ=,tag:Bw3LH/WtesidbrwY5SMOcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSEcxWXRaSWYvdjJEekxM
            NllCaUhSaWdtZDM0K3hMUGx6ajNoK3YwMkRBCjZENDVZdmNOZG9PWnBwNko3UDMx
            aVdud0l2cTdhYURkLzNUTTB5L2hFS0kKLS0tIGxlcVZkekFZc0trZis1a0xNZlp6
            U2d6ODVvVFJVWkNFdk5XeVlIVUlnRlUK6Jed1m/O3sP+ddmp2ZTecZqscDZGUgL2
            77CHfPb0WUmJF+jm4UYn40Iqj18lNvVsOT2JmGxIWpKnBEX+livDhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T06:43:57Z"
    mac: ENC[AES256_GCM,data:XCU7FFq9ssXmz7FyQe9ggVNvjSi6bcu888K+s8PwLqUigiip6IZ3wMFcMmosqMjvXOMlcl+AZsS4eDcs7NPmwQw0ikNU9+wQOAOWuofNNs038KIwPO7fjAT/6QyUim71iu1I6pRqVZ6kGlQai5JlA9/2oe1NCtC83p6CoXe5lzg=,iv:1+u8iRYOEHBYNg9pMEfO/6WDHI0Nh1YCVV/hA2CbkLc=,tag:vdgM5klNdEtGC7UBIOyOBg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
